export default [
  {
    personId: "aaaa07f32e75430ea93ac749",
    fullName: "Gill Mison",
    title: "Chief Customer Officer",
    linkedinUrl: "https://www.linkedin.com/in/gillmison",
    companyDomain: "oakfurnitureland.co.uk",
  },
  {
    personId: "aaaa0ffb219bee5440764447",
    fullName: "Alex Fisher",
    title: "Chief Executive Officer",
    linkedinUrl: "https://www.linkedin.com/in/alex-fisher-a268089",
    companyDomain: "oakfurnitureland.co.uk",
  },
  {
    personId: "aaaa1e2d330f285af7bb6b3d",
    fullName: "Suzy Mcmahon",
    title: "Chief Commercial Officer",
    linkedinUrl: "https://www.linkedin.com/in/suzy-mcmahon-1b479093",
    companyDomain: "oakfurnitureland.co.uk",
  },
  {
    personId: "aaaa8dbf99e1257b57b9c665",
    fullName: "David Hennessy",
    title: "Chief Information Officer",
    linkedinUrl: "https://www.linkedin.com/in/dahennessy",
    companyDomain: "oakfurnitureland.co.uk",
  },
  {
    personId: "aaaae1f8ac88dd7e3f3e0d69",
    fullName: "Paul Burgham",
    title: "Retail & Property Director",
    linkedinUrl: "https://www.linkedin.com/in/paul-burgham-3a87a65b",
    companyDomain: "oakfurnitureland.co.uk",
  },
  {
    personId: "aaaac9e623ad3b6cb64ee964",
    fullName: "Julia Schönhofen",
    title: "Business Development & Growth Management | CEO‘s Office",
    linkedinUrl: "https://www.linkedin.com/in/julia-schönhofen-51948696",
    companyDomain: "kare.de",
  },
  {
    personId: "aaaa91d61937c2bd10ee034d",
    fullName: "Alexander Matschl",
    title: "Chief Financial Officer",
    linkedinUrl: "https://www.linkedin.com/in/alexander-matschl-864452a",
    companyDomain: "kare.de",
  },
  {
    personId: "aaaa300d89f9bd6e37f097d9",
    fullName: "Natalie Schön",
    title: "Artdirektor",
    linkedinUrl: "https://www.linkedin.com/in/natalie-schön-282700192",
    companyDomain: "kare.de",
  },
  {
    personId: "aaaa18fac3fc2251a425450c",
    fullName: "Christoph Frey",
    title: "Inhaber",
    linkedinUrl: "https://www.linkedin.com/in/christoph-frey-61536212",
    companyDomain: "kare.de",
  },
  {
    personId: "aaaa3faedd5ca15aa894373f",
    fullName: "Michl Wolf",
    title: "Chief Operations Officer",
    linkedinUrl: "https://www.linkedin.com/in/michl-wolf-33b091110",
    companyDomain: "kare.de",
  },
  {
    personId: "aaaa2e0deed31e3f383959a5",
    fullName: "Denys Lavoie",
    title: "National sale director and customer experience",
    linkedinUrl: "https://www.linkedin.com/in/denys-lavoie-97842977",
    companyDomain: "mobilia.ca",
  },
  {
    personId: "aaaaf70fde96023e1d830be0",
    fullName: "Hubmaj Gecko",
    title: "Directeur",
    linkedinUrl: "https://www.linkedin.com/in/hubmaj-gecko-1818b493",
    companyDomain: "mobilia.ca",
  },
  {
    personId: "aaaab3c6fd7f0b10a3013604",
    fullName: "Mobilia A P De Carva Mobilia",
    title: "proprietaria",
    linkedinUrl:
      "https://www.linkedin.com/in/mobilia-a-p-de-carva-mobilia-5a092967",
    companyDomain: "mobilia.ca",
  },
  {
    personId: "aaaab832b28231abb290ebbf",
    fullName: "Mohamed Karim Chraibi",
    title: "Directeur général adjoint",
    linkedinUrl: "https://www.linkedin.com/in/mohamed-karim-chraibi-a3172754",
    companyDomain: "mobilia.ca",
  },
  {
    personId: "aaaabae3bc297e239f4ff448",
    fullName: "Yasser Ferssiwi",
    title: "directeur des achats & approvisionnements",
    linkedinUrl: "https://www.linkedin.com/in/yasser-ferssiwi-b110b540",
    companyDomain: "mobilia.ca",
  },
];
